{
 "title": "Application Health (SRE)",
 "time": { "from": "2026-02-24T17:07:57.896Z", "to": "2026-03-04T20:11:53.147Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "SRE Welcome Panel",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Bienvenue sur le Dashboard SRE"
   }
  },
  {
   "title": "Utilisation Mémoire",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "francecentral",
        "resourceGroup": "rg-projet1-lab",
        "resourceName": "app-projet1-55906d7d9b",
        "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
    }
   ]
  },
  {
   "title": "Total Traffic (Requêtes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "francecentral",
        "resourceGroup": "rg-projet1-lab",
        "resourceName": "app-projet1-55906d7d9b",
        "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
    }
   ]
  },
  {
   "title": "Saturation CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuTime",
      "metricNamespace": "microsoft.web/sites",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "francecentral",
        "resourceGroup": "rg-projet1-lab",
        "resourceName": "app-projet1-55906d7d9b",
        "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
    }
   ]
  },
  {
   "title": "Erreurs Client (400)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http4xx",
      "metricNamespace": "microsoft.web/sites",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "francecentral",
        "resourceGroup": "rg-projet1-lab",
        "resourceName": "app-projet1-55906d7d9b",
        "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
    }
   ]
  },
  {
   "title": "Temps de Réponse Moyen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricName": "Average Response Time",
      "metricNamespace": "microsoft.web/sites",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "francecentral",
        "resourceGroup": "rg-projet1-lab",
        "resourceName": "app-projet1-55906d7d9b",
        "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
    }
   ]
  },
  {
   "title": "Erreurs Serveur (500)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Microsoft.Web/sites",
      "dimensionFilters": [],
      "metricName": "Http 5xx",
      "metricNamespace": "microsoft.web/sites",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "francecentral",
        "resourceGroup": "rg-projet1-lab",
        "resourceName": "app-projet1-55906d7d9b",
        "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "0f3b6c74-e6a7-46dd-bf2f-079c4568c1c2"
    }
   ]
  }
 ]
}